### ISSUE TITLE
FreshMVVM works fine in windows app (UWP) but in android it throws error unable to resolve as below

### ISSUE THREAD

**Issue by Samirliving** [rid00z/FreshMvvm#224]
04-10 13:36:13.960: I/MonoDroid(5160): UNHANDLED EXCEPTION:
04-10 13:36:14.044: I/MonoDroid(5160): FreshTinyIoC.TinyIoCResolutionException: Resolve failed: LoginPageModel
04-10 13:36:14.044: I/MonoDroid(5160):   at FreshTinyIoC.FreshTinyIoCContainer.ConstructType (System.Type requestedType, System.Type implementationType, System.Reflection.ConstructorInfo constructor, FreshTinyIoC.NamedParameterOverloads parameters, FreshTinyIoC.ResolveOptions options) [0x0005f] in <fafbc3658d2648afa95b5e3a4ba67ae2>:0 
04-10 13:36:14.044: I/MonoDroid(5160):   at FreshTinyIoC.FreshTinyIoCContainer.ConstructType (System.Type requestedType, System.Type implementationType, FreshTinyIoC.NamedParameterOverloads parameters, FreshTinyIoC.ResolveOptions options) [0x00000] in <fafbc3658d2648afa95b5e3a4ba67ae2>:0 
04-10 13:36:14.044: I/MonoDroid(5160):   at FreshTinyIoC.FreshTinyIoCContainer.ResolveInternal (FreshTinyIoC.FreshTinyIoCContainer+TypeRegistration registration, FreshTinyIoC.NamedParameterOverloads parameters, FreshTinyIoC.ResolveOptions options) [0x001ba] in <fafbc3658d2648afa95b5e3a4ba67ae2>:0 
04-10 13:36:14.044: I/MonoDroid(5160):   at FreshTinyIoC.FreshTinyIoCContainer.Resolve (System.Type resolveType) [0x00011] in <fafbc3658d2648afa95b5e3a4ba67ae2>:0 
04-10 13:36:14.044: I/MonoDroid(5160):   at FreshTinyIoC.FreshTinyIoCContainer.Resolve[ResolveType] () [0x00000] in <fafbc3658d2648afa95b5e3a4ba67ae2>:0 
04-10 13:36:14.044: I/MonoDroid(5160):   at FreshMvvm.FreshTinyIOCBuiltIn.Resolve[ResolveType] () [0x00005] in <69b1d8a9531e444bbbbbcc61e9132c27>:0 
04-10 13:36:14.044: I/MonoDroid(5160):   at FreshMvvm.FreshPageModelResolver.ResolvePageModel[T] (System.Object initData) [0x00005] in <69b1d8a9531e444bbbbbcc61e9132c27>:0 
04-10 13:36:14.044: I/MonoDroid(5160):   at XTest3.App..ctor () [0x00016] in <d63a3bb88cca4dc58a6333f5c5f8713d>:0 
04-10 13:36:14.044: I/MonoDroid(5160):   at XTest3.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00042] in <f978acc7e56e403497ec527a5cf58fa3>:0 
04-10 13:36:14.044: I/MonoDroid(5160):   at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <71c87dcc676146dda716fb014e36786b>:0 
04-10 13:36:14.044: I/MonoDroid(5160):   at (wrapper dynamic-method) System.Object.73bbfda8-f2c1-44d6-88c6-1e9ad10c9223(intptr,intptr,intptr)
04-10 13:36:14.063: W/art(5160): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
04-10 13:36:14.080: D/Mono(5160): DllImport searching in: '__Internal' ('(null)').
04-10 13:36:14.080: D/Mono(5160): Searching for 'java_interop_jnienv_throw'.
04-10 13:36:14.080: D/Mono(5160): Probing 'java_interop_jnienv_throw'.
04-10 13:36:14.080: D/Mono(5160): Found as 'java_interop_jnienv_throw'.
04-10 13:36:14.083: D/AndroidRuntime(5160): Shutting down VM
04-10 13:36:14.101: E/AndroidRuntime(5160): FATAL EXCEPTION: main
04-10 13:36:14.101: E/AndroidRuntime(5160): Process: XTest3.Android, PID: 5160
04-10 13:36:14.101: E/AndroidRuntime(5160): android.runtime.JavaProxyThrowable: FreshTinyIoC.TinyIoCResolutionException: Resolve failed: LoginPageModel
04-10 13:36:14.101: E/AndroidRuntime(5160):   at FreshTinyIoC.FreshTinyIoCContainer.ConstructType (System.Type requestedType, System.Type implementationType, System.Reflection.ConstructorInfo constructor, FreshTinyIoC.NamedParameterOverloads parameters, FreshTinyIoC.ResolveOptions options) [0x0005f] in <fafbc3658d2648afa95b5e3a4ba67ae2>:0 
04-10 13:36:14.101: E/AndroidRuntime(5160):   at FreshTinyIoC.FreshTinyIoCContainer.ConstructType (System.Type requestedType, System.Type implementationType, FreshTinyIoC.NamedParameterOverloads parameters, FreshTinyIoC.ResolveOptions options) [0x00000] in <fafbc3658d2648afa95b5e3a4ba67ae2>:0 
04-10 13:36:14.101: E/AndroidRuntime(5160):   at FreshTinyIoC.FreshTinyIoCContainer.ResolveInternal (FreshTinyIoC.FreshTinyIoCContainer+TypeRegistration registration, FreshTinyIoC.NamedParameterOverloads parameters, FreshTinyIoC.ResolveOptions options) [0x001ba] in <fafbc3658d2648afa95b5e3a4ba67ae2>:0 
04-10 13:36:14.101: E/AndroidRuntime(5160):   at FreshTinyIoC.FreshTinyIoCContainer.Resolve (System.Type resolveType) [0x00011] in <fafbc3658d2648afa95b5e3a4ba67ae2>:0 
04-10 13:36:14.101: E/AndroidRuntime(5160):   at FreshTinyIoC.FreshTinyIoCContainer.Resolve[ResolveType] () [0x00000] in <fafbc3658d2648afa95b5e3a4ba67ae2>:0 
04-10 13:36:14.101: E/AndroidRuntime(5160):   at FreshMvvm.FreshTinyIOCBuiltIn.Resolve[ResolveType] () [0x00005] in <69b1d8a9531e444bbbbbcc61e9132c27>:0 
04-10 13:36:14.101: E/AndroidRuntime(5160):   at FreshMvvm.FreshPageModelResolver.ResolvePageModel[T] (System.Object initData) [0x00005] in <69b1d8a9531e444bbbbbcc61e9132c27>:0 
04-10 13:36:14.101: E/AndroidRuntime(5160):   at XTest3.App..ctor () [0x00016] in <d63a3bb88cca4dc58a6333f5c5f8713d>:0 
04-10 13:36:14.101: E/AndroidRuntime(5160):   at XTest3.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00042] in <f978acc7e56e403497ec527a5cf58fa3>:0 
04-10 13:36:14.101: E/AndroidRuntime(5160):   at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <71c87dcc676146dda716fb014e36786b>:0 
04-10 13:36:14.101: E/AndroidRuntime(5160):   at (wrapper dynamic-method) System.Object.73bbfda8-f2c1-44d6-88c6-1e9ad10c9223(intptr,intptr,intptr)
04-10 13:36:14.101: E/AndroidRuntime(5160): 	at md5d9e51778fe899499af6e56a25dfadf4e.MainActivity.n_onCreate(Native Method)
04-10 13:36:14.101: E/AndroidRuntime(5160): 	at md5d9e51778fe899499af6e56a25dfadf4e.MainActivity.onCreate(MainActivity.java:29)
04-10 13:36:14.101: E/AndroidRuntime(5160): 	at android.app.Activity.performCreate(Activity.java:6679)
04-10 13:36:14.101: E/AndroidRuntime(5160): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
04-10 13:36:14.101: E/AndroidRuntime(5160): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
04-10 13:36:14.101: E/AndroidRuntime(5160): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
04-10 13:36:14.101: E/AndroidRuntime(5160): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
04-10 13:36:14.101: E/AndroidRuntime(5160): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
04-10 13:36:14.101: E/AndroidRuntime(5160): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-10 13:36:14.101: E/AndroidRuntime(5160): 	at android.os.Looper.loop(Looper.java:154)
04-10 13:36:14.101: E/AndroidRuntime(5160): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
04-10 13:36:14.101: E/AndroidRuntime(5160): 	at java.lang.reflect.Method.invoke(Native Method)
04-10 13:36:14.101: E/AndroidRuntime(5160): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-10 13:36:14.101: E/AndroidRuntime(5160): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
04-10 13:36:14.115: W/ActivityManager(1571):   Force finishing activity XTest3.Android/md5d9e51778fe899499af6e56a25dfadf4e.MainActivity

**Comment by Samirliving** [comment]
Unhandled Exception:

FreshTinyIoC.TinyIoCResolutionException: <Timeout exceeded getting exception details>

**Comment by Samirliving** [comment]
Please help i am stuck on this issue for past few days.. will really appreciate your help. Thank you in advance.

**Comment by MikeCodesDotNet** [comment]
Can you provide a repro project?

**Comment by Samirliving** [comment]
sorry about iOS issue reporting, it is working fine on iOS. just Android issue.. 

04-12 15:17:08.049 D/Mono    ( 4468): Assembly Ref addref Xamarin.Forms.Xaml[0x91b699c0] -> System.Core[0x91b6a3e0]: 7
Unhandled Exception:

FreshTinyIoC.TinyIoCResolutionException: <Timeout exceeded getting exception details>

04-12 15:17:48.495 D/Mono    ( 4468): DllImport attempting to load: '/system/lib/liblog.so'.
04-12 15:17:48.518 D/Mono    ( 4468): DllImport loaded library '/system/lib/liblog.so'.
04-12 15:17:51.825 D/Mono    ( 4468): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
04-12 15:17:51.825 D/Mono    ( 4468): Searching for '__android_log_print'.
04-12 15:17:51.825 D/Mono    ( 4468): Probing '__android_log_print'.
04-12 15:17:51.825 D/Mono    ( 4468): Found as '__android_log_print'.
04-12 15:17:53.576 I/MonoDroid( 4468): UNHANDLED EXCEPTION:
04-12 15:17:55.594 I/MonoDroid( 4468): FreshTinyIoC.TinyIoCResolutionException: Resolve failed: LoginPageModel
04-12 15:17:55.595 I/MonoDroid( 4468):   at FreshTinyIoC.FreshTinyIoCContainer.ConstructType (System.Type requestedType, System.Type implementationType, System.Reflection.ConstructorInfo constructor, FreshTinyIoC.NamedParameterOverloads parameters, FreshTinyIoC.ResolveOptions options) [0x0005f] in <20d763c808014841bf981896d5015170>:0 
04-12 15:17:55.595 I/MonoDroid( 4468):   at FreshTinyIoC.FreshTinyIoCContainer.ConstructType (System.Type requestedType, System.Type implementationType, FreshTinyIoC.NamedParameterOverloads parameters, FreshTinyIoC.ResolveOptions options) [0x00000] in <20d763c808014841bf981896d5015170>:0 
04-12 15:17:55.595 I/MonoDroid( 4468):   at FreshTinyIoC.FreshTinyIoCContainer.ResolveInternal (FreshTinyIoC.FreshTinyIoCContainer+TypeRegistration registration, FreshTinyIoC.NamedParameterOverloads parameters, FreshTinyIoC.ResolveOptions options) [0x001ba] in <20d763c808014841bf981896d5015170>:0 
04-12 15:17:55.595 I/MonoDroid( 4468):   at FreshTinyIoC.FreshTinyIoCContainer.Resolve (System.Type resolveType) [0x00011] in <20d763c808014841bf981896d5015170>:0 
04-12 15:17:55.595 I/MonoDroid( 4468):   at FreshTinyIoC.FreshTinyIoCContainer.Resolve[ResolveType] () [0x00000] in <20d763c808014841bf981896d5015170>:0 
04-12 15:17:55.595 I/MonoDroid( 4468):   at FreshMvvm.FreshTinyIOCBuiltIn.Resolve[ResolveType] () [0x00000] in /Users/michaelridland/Projects/FreshMvvm/src/FreshMvvm/FreshTinyIOCBuiltIn.cs:36 
04-12 15:17:55.596 I/MonoDroid( 4468):   at FreshMvvm.FreshPageModelResolver.ResolvePageModel[T] (System.Object initData) [0x00000] in /Users/michaelridland/Projects/FreshMvvm/src/FreshMvvm/FreshPageModelResolver.cs:17 
04-12 15:17:55.596 I/MonoDroid( 4468):   at XTest3.App..ctor () [0x00016] in C:\TFS\XPOS\XTest3\XTest3\App.xaml.cs:24 
04-12 15:17:55.602 I/MonoDroid( 4468):   at XTest3.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00042] in C:\TFS\XPOS\XTest3\XTest3.Android\MainActivity.cs:26 
04-12 15:17:55.602 I/MonoDroid( 4468):   at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <7e889aca15b34c74a50abd44173fede9>:0 
04-12 15:17:55.602 I/MonoDroid( 4468):   at (wrapper dynamic-method) System.Object.ccb2304c-8773-49b5-9555-ea7d0e6dafd7(intptr,intptr,intptr)
04-12 15:17:55.921 W/art     ( 4468): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
04-12 15:17:56.026 D/Mono    ( 4468): DllImport searching in: '__Internal' ('(null)').
04-12 15:17:56.026 D/Mono    ( 4468): Searching for 'java_interop_jnienv_throw'.
04-12 15:17:56.026 D/Mono    ( 4468): Probing 'java_interop_jnienv_throw'.
04-12 15:17:56.026 D/Mono    ( 4468): Found as 'java_interop_jnienv_throw'.
An unhandled exception occured.

04-12 15:17:59.279 E/mono    ( 4468): 
04-12 15:17:59.279 E/mono    ( 4468): Unhandled Exception:
04-12 15:17:59.279 E/mono    ( 4468): FreshTinyIoC.TinyIoCResolutionException: Resolve failed: LoginPageModel
04-12 15:17:59.279 E/mono    ( 4468):   at (wrapper dynamic-method) System.Object.ccb2304c-8773-49b5-9555-ea7d0e6dafd7(intptr,intptr,intptr)
04-12 15:17:59.280 E/mono-rt ( 4468): [ERROR] FATAL UNHANDLED EXCEPTION: FreshTinyIoC.TinyIoCResolutionException: Resolve failed: LoginPageModel
04-12 15:17:59.280 E/mono-rt ( 4468):   at (wrapper dynamic-method) System.Object.ccb2304c-8773-49b5-9555-ea7d0e6dafd7(intptr,intptr,intptr)

**Comment by marcoseraphin** [comment]
This error often occurs when a page could not be initialized.
Unfortunately this is a general error of the IoC container and sometimes the exact line in the page with forces the error could not be find easily.
The page could not be resolved because of errors in the logic code of the page (constructor and other initial code) or XAML errors.

Try to comment out the XAML code of the page unless a simple label.
Check your initial code in the OnAppearing method if you have code there and in your constructor.
Try to run the app and the direct initialized page without your UI and logic code....and if the simple page runs without errors carefully comment in your code again in some pieces and start the app.

Mostly it is a XAML problem.

Best

Marco

**Comment by maherzaidoune** [comment]
can you post your LoginPageModel and LoginPage code ? make sure you respect the naming convention for page and pageModel and make sure your LoginPageModel override the Init method

**Comment by EmilAlipiev** [comment]
he claims that it works for uwp and ios, i dont think that it is problem with his conventions unless he uses loginpage and loginpagemodel for only android. it is probably a linker issue in android. do you use full linking?

**Comment by egedib** [comment]
Right click Android solution -> Properties -> Android Options

What is selected under Linking? I guess "SDK and User assemblies". Choose 'SDK Assemblies only'. Or 'None'.

**Comment by EmilAlipiev** [comment]
if you found a solution, you should close this ticket, otherwise give us more information. I am 100% sure that this is your coding mistake or you dont understand the concept of android and it has nothing to do with this library.

**Comment by dean-toolhound** [comment]
I am having a similar problem except it works perfectly in Android but not on iOS.

var page = FreshPageModelResolver.ResolvePageModel<LoginPageModel>();

FreshTinyIoC.TinyIoCResolutionException: Resolve failed: LoginPageModel

I have tried different models in my project with the same result.

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at THPhone.Application..ctor () [0x00048] in D:\THPhone\THPhone\THPhone\App.xaml.cs:38 
  at THPhone.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x00019] in <e00e36a9d8374d0c8471524e205fe532>:0 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/UIKit/UIApplication.cs:63 
  at THPhone.iOS.Application.Main (System.String[] args) [0x0000
1] in <e00e36a9d8374d0c8471524e205fe532>:0 
2018-10-02 15:00:02.658 THPhone.iOS[18679:482292] Unhandled managed exception:
Object reference not set to an instance of an object (System.NullReferenceException)
  at THPhone.Application..ctor () [0x00048] in D:\THPhone\THPhone\THPhone\App.xaml.cs:38 
  at THPhone.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x00019] in <e00e36a9d8374d0c8471524e205fe532>:0 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/UIKit/UIApplication.cs:63 
  at THPhone
.iOS.Application.Main (System.String[] args) [0x00001] in <e00e36a9d8374d0c8471524e205fe532>:0 
2018-10-02 15:00:02.658 THPhone.iOS[18679:482292] critical: Stacktrace:

2018-10-02 15:00:02.659 THPhone.iOS[18679:482292] critical: 
Native stacktrace:
2018-10-02 15:00:02.664 THPhone.iOS[18679:482292] critical: 	0   THPhone.iOS                         0x0000000104c8e3f4 mono_handle_native_crash + 244
2018-10-02 15:00:02.664 THPhone.iOS[18679:482292] critical: 	1   libsystem_platform.dylib            0x000000010a34af5a _sigtramp + 26
2018-10-02 15:00:02.664 THPhone.iOS[18679:482292] critical: 	2   ???                                 0x00000001050b7fd0 0x0 + 4379606992
2018-10-02 15:00:02.665 THPhone.iOS[18679:482292] critical: 	3   libsystem_c.dylib                   0x000000010a0d2c45 abort + 127
2018-10-02 15:00:02.665 THPhone.iOS[18679:482292] critical: 	4   THPhone.iOS                         0x0000000104e673df xamarin_unhandled_exception_handler + 47
2018-10-02 15:00:02.665 THPhone.iOS[18679:482292] critical: 	5   THPhone.iOS                         0x0000000104d2574e mono_invoke_unhandled_exception_hook + 158
2018-10-02 15:00:02.665 THPhone.iOS[18679:482292] critical: 	6   THPhone.iOS                         0x0000000104c8dfc0 mono_handle_exception_internal + 6240
2018-10-02 15:00:02.665 THPhone.iOS[18679:482292] critical: 	7   THPhone.iOS                         0x0000000104c8c759 mono_handle_exception + 25
2018-10-02 15:00:02.665 THPhone.iOS[18679:482292] critical: 	8   THPhone.iOS                         0x0000000104c0e4a9 handle_signal_exception + 57
2018-10-02 15:00:02.666 THPhone.iOS[18679:482292] critical: 	9   ???                                 0x00007ffeeb031698 0x0 + 140732841268888
2018-10-02 15:00:02.666 THPhone.iOS[18679:482292] critical: 	10  ???                                 0x000000012d669d43 0x0 + 5056666947
2018-10-02 15:00:02.666 THPhone.iOS[18679:482292] critical: 	11  THPhone.iOS                         0x0000000104c9ffa3 mono_jit_runtime_invoke + 1443
2018-10-02 15:00:02.666 THPhone.iOS[18679:482292] critical: 	12  THPhone.iOS                         0x0000000104d8619f mono_runtime_invoke_checked + 127
2018-10-02 15:00:02.666 THPhone.iOS[18679:482292] critical: 	13  THPhone.iOS                         0x0000000104d89993 mono_runtime_invoke + 83
2018-10-02 15:00:02.666 THPhone.iOS[18679:482292] critical: 	14  THPhone.iOS                         0x0000000104e70292 xamarin_invoke_trampoline + 6018
2018-10-02 15:00:02.667 THPhone.iOS[18679:482292] critical: 	15  THPhone.iOS                         0x0000000104e76d7d xamarin_arch_trampoline + 189
2018-10-02 15:00:02.667 THPhone.iOS[18679:482292] critical: 	16  THPhone.iOS                         0x0000000104e781b1 xamarin_x86_64_common_trampoline + 110
2018-10-02 15:00:02.667 THPhone.iOS[18679:482292] critical: 	17  UIKitCore                           0x000000010ee264d7 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 280
2018-10-02 15:00:02.667 THPhone.iOS[18679:482292] critical: 	18  UIKitCore                           0x000000010ee27ec4 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3979
2018-10-02 15:00:02.668 THPhone.iOS[18679:482292] critical: 	19  UIKitCore                           0x000000010ee2d527 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1623
2018-10-02 15:00:02.668 THPhone.iOS[18679:482292] critical: 	20  UIKitCore                           0x000000010f6cfe3e __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 866
2018-10-02 15:00:02.668 THPhone.iOS[18679:482292] critical: 	21  UIKitCore                           0x000000010f6cc403 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
2018-10-02 15:00:02.668 THPhone.iOS[18679:482292] critical: 	22  UIKitCore                           0x000000010f6cfa7b -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 233
2018-10-02 15:00:02.669 THPhone.iOS[18679:482292] critical: 	23  UIKitCore                           0x000000010f6d0435 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 1085
2018-10-02 15:00:02.669 THPhone.iOS[18679:482292] critical: 	24  UIKitCore                           0x000000010f68db31 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 795
2018-10-02 15:00:02.669 THPhone.iOS[18679:482292] critical: 	25  UIKitCore                           0x000000010f68d7db -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 435
2018-10-02 15:00:02.670 THPhone.iOS[18679:482292] critical: 	26  UIKitCore                           0x000000010f6d292c __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 584
2018-10-02 15:00:02.670 THPhone.iOS[18679:482292] critical: 	27  UIKitCore                           0x000000010f6d3256 _performActionsWithDelayForTransitionContext + 100
2018-10-02 15:00:02.670 THPhone.iOS[18679:482292] critical: 	28  UIKitCore                           0x000000010f6d268b -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 221
2018-10-02 15:00:02.670 THPhone.iOS[18679:482292] critical: 	29  UIKitCore                           0x000000010f6cbaa1 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
2018-10-02 15:00:02.671 THPhone.iOS[18679:482292] critical: 	30  UIKitCore                           0x000000010ee2bd46 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 515
2018-10-02 15:00:02.671 THPhone.iOS[18679:482292] critical: 	31  UIKitCore                           0x000000010ee5d856 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 357
2018-10-02 15:00:02.671 THPhone.iOS[18679:482292] critical: 	32  FrontBoardServices                  0x0000000115b9fdda -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 448
2018-10-02 15:00:02.671 THPhone.iOS[18679:482292] critical: 	33  FrontBoardServices                  0x0000000115baaf43 __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 271
2018-10-02 15:00:02.672 THPhone.iOS[18679:482292] critical: 	34  FrontBoardServices                  0x0000000115baa63a __40-[FBSWorkspace _performDelegateCallOut:]_block_invoke + 53
2018-10-02 15:00:02.672 THPhone.iOS[18679:482292] critical: 	35  libdispatch.dylib                   0x0000000109f76587 _dispatch_client_callout + 8
2018-10-02 15:00:02.672 THPhone.iOS[18679:482292] critical: 	36  libdispatch.dylib                   0x0000000109f79647 _dispatch_block_invoke_direct + 312
2018-10-02 15:00:02.672 THPhone.iOS[18679:482292] critical: 	37  FrontBoardServices                  0x0000000115bdf3c8 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
2018-10-02 15:00:02.673 THPhone.iOS[18679:482292] critical: 	38  FrontBoardServices                  0x0000000115bdf080 -[FBSSerialQueue _performNext] + 457
2018-10-02 15:00:02.673 THPhone.iOS[18679:482292] critical: 	39  FrontBoardServices                  0x0000000115bdf660 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
2018-10-02 15:00:02.673 THPhone.iOS[18679:482292] critical: 	40  CoreFoundation                      0x0000000107ba4b31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
2018-10-02 15:00:02.673 THPhone.iOS[18679:482292] critical: 	41  CoreFoundation                      0x0000000107ba43a3 __CFRunLoopDoSources0 + 243
2018-10-02 15:00:02.674 THPhone.iOS[18679:482292] critical: 	42  CoreFoundation                      0x0000000107b9ea4f __CFRunLoopRun + 1263
2018-10-02 15:00:02.674 THPhone.iOS[18679:482292] critical: 	43  CoreFoundation                      0x0000000107b9e221 CFRunLoopRunSpecific + 625
2018-10-02 15:00:02.674 THPhone.iOS[18679:482292] critical: 	44  GraphicsServices                    0x0000000111d391dd GSEventRunModal + 62
2018-10-02 15:00:02.674 THPhone.iOS[18679:482292] critical: 	45  UIKitCore                           0x000000010ee2f115 UIApplicationMain + 140
2018-10-02 15:00:02.675 THPhone.iOS[18679:482292] critical: 	46  ???                                 0x000000012d295ace 0x0 + 5052652238
2018-10-02 15:00:02.675 THPhone.iOS[18679:482292] critical: 	47  ???                                 0x000000012d295863 0x0 + 5052651619
2018-10-02 15:00:02.675 THPhone.iOS[18679:482292] critical: 
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

**Comment by dean-toolhound** [comment]
Thanks for the quick reply Emil. 

Why does the complete app work perfectly fine in Android but not on iOS? I have also tried a completely different model and I get the same result. Both models with associated pages work in Android so the XAML must be correct.

I also removed everything from the XAML except for a label and I still get the same results.

**Comment by dean-toolhound** [comment]
I assume it must be something else and may not be directly related to FreshMVVM but just looking for ideas.

**Comment by ankittyagi366** [comment]
This issue is happening in Android & iOS only and works for UWP . The solution of this issue is - 
Android
Go to Android Properties - > Android options -> Linking - > Set to SDK Assemblies  

iOS

iOS Propeties -> iOS Build -> Linking -> Set to Link framework SDK's Only

Let me know if still facing this issue

**Comment by lmguerrero920** [comment]
Hola amigos de la comunidad , la solución que encontré y fue lo extraño es que por ejemplo: primero lo tenia asi:
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             Visual="Material"
             Title="{Binding GroupName,StringFormat='{0} -Sala'}"
             x:Class="TheChat.Pages.ChatPage">
 
         
    <Grid RowSpacing="0">


Lo que hice fue quitar       Visual="Material"  y ya funciono, obviamente no es una solución correcta pero bueno,es mejor que compile a que
